# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Asistencia Bancoppel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Asistencia Bancoppel
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end